# Generated by Django 2.0.1 on 2018-01-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180112_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
